# Generated by Django 3.2.3 on 2021-05-29 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gql1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
